name: privacy_app
description: "Privacy App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_apps: ^2.2.0   # latest version
  permission_handler: ^11.4.0
  shared_preferences:
  http: ^1.5.0
  url_launcher: ^6.3.2
  fl_chart: ^0.70.0
  pdf: ^3.10.0
  intl: ^0.19.0
  path_provider: ^2.1.0
  flutter_local_notifications: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
